version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
    # requires manual update of `.nvmrc` and `package.json`
    - dependency-name: "@types/node"
